import React from 'react';
import { X, Sparkles } from 'lucide-react';

interface AiAnalysisModalProps {
  isOpen: boolean;
  onClose: () => void;
  analysis: string;
}

const AiAnalysisModal: React.FC<AiAnalysisModalProps> = ({ isOpen, onClose, analysis }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-brand-black/60 backdrop-blur-sm p-4">
      <div className="bg-brand-white rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden animate-in zoom-in-95 duration-200 flex flex-col max-h-[85vh] border border-brand-grey">
        <div className="px-6 py-4 border-b border-brand-blue/10 flex justify-between items-center bg-brand-blue/5">
          <div className="flex items-center gap-2 font-bold text-brand-blue">
            <Sparkles className="w-5 h-5 fill-current" />
            AI Productivity Insights
          </div>
          <button onClick={onClose} className="p-1 hover:bg-brand-grey rounded-full transition-colors">
            <X className="w-5 h-5 text-brand-darkGrey" />
          </button>
        </div>

        <div className="p-6 overflow-y-auto bg-brand-white">
            <div className="prose prose-sm max-w-none text-brand-black">
                {/* 
                  The analysis comes as plain text from the simple prompt, 
                  but we can wrap lines in paragraphs for better readability.
                */}
                {analysis.split('\n').map((paragraph, index) => (
                    paragraph.trim() && <p key={index} className="mb-3 leading-relaxed border-l-2 border-brand-blue/20 pl-4">{paragraph}</p>
                ))}
            </div>
            
            <div className="mt-6 p-4 bg-brand-grey/30 rounded-xl border border-brand-grey">
                <p className="text-xs text-brand-darkGrey text-center font-bold uppercase tracking-wide">
                    Insights generated by Gemini 2.5 Flash
                </p>
            </div>
        </div>

        <div className="p-4 border-t border-brand-grey bg-brand-grey/10">
             <button
            onClick={onClose}
            className="w-full py-3 bg-brand-white border border-brand-grey hover:bg-brand-grey text-brand-black rounded-xl font-bold transition-colors uppercase tracking-wide text-sm"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};

export default AiAnalysisModal;